import React from 'react';
import { X, Printer } from 'lucide-react';
import { Button } from './ui/button';

// Function to convert number to Indonesian words
function numberToWords(num) {
  const ones = ['', 'satu', 'dua', 'tiga', 'empat', 'lima', 'enam', 'tujuh', 'delapan', 'sembilan'];
  const tens = ['', '', 'dua puluh', 'tiga puluh', 'empat puluh', 'lima puluh', 'enam puluh', 'tujuh puluh', 'delapan puluh', 'sembilan puluh'];
  const teens = ['sepuluh', 'sebelas', 'dua belas', 'tiga belas', 'empat belas', 'lima belas', 'enam belas', 'tujuh belas', 'delapan belas', 'sembilan belas'];

  if (num === 0) return 'nol';
  if (num < 10) return ones[num];
  if (num >= 10 && num < 20) return teens[num - 10];
  if (num >= 20 && num < 100) {
    const ten = Math.floor(num / 10);
    const one = num % 10;
    return tens[ten] + (one > 0 ? ' ' + ones[one] : '');
  }
  if (num >= 100 && num < 200) {
    const remainder = num % 100;
    return 'seratus' + (remainder > 0 ? ' ' + numberToWords(remainder) : '');
  }
  if (num >= 200 && num < 1000) {
    const hundred = Math.floor(num / 100);
    const remainder = num % 100;
    return ones[hundred] + ' ratus' + (remainder > 0 ? ' ' + numberToWords(remainder) : '');
  }
  if (num >= 1000 && num < 2000) {
    const remainder = num % 1000;
    return 'seribu' + (remainder > 0 ? ' ' + numberToWords(remainder) : '');
  }
  if (num >= 2000 && num < 1000000) {
    const thousand = Math.floor(num / 1000);
    const remainder = num % 1000;
    return numberToWords(thousand) + ' ribu' + (remainder > 0 ? ' ' + numberToWords(remainder) : '');
  }
  if (num >= 1000000 && num < 1000000000) {
    const million = Math.floor(num / 1000000);
    const remainder = num % 1000000;
    return numberToWords(million) + ' juta' + (remainder > 0 ? ' ' + numberToWords(remainder) : '');
  }
  return num.toString();
}

export function DirectSalesInvoiceModal({
  isOpen,
  selectedSale,
  onClose,
  formatCurrency,
  onGenerateInvoiceNumber
}) {
  const [isInvoicePrinted, setIsInvoicePrinted] = React.useState(false);

  // Reset state when modal opens/closes
  React.useEffect(() => {
    if (!isOpen) {
      setIsInvoicePrinted(false);
    }
  }, [isOpen]);

  // Handle print and generate invoice number on first print
  React.useEffect(() => {
    const afterPrint = () => {
      setIsInvoicePrinted(true);
      // Generate invoice number on first print
      if (selectedSale && !selectedSale.invoiceNumber) {
        onGenerateInvoiceNumber(selectedSale.id);
      }
      // Auto close modal after print
      setTimeout(() => {
        onClose();
      }, 500);
    };

    window.addEventListener('afterprint', afterPrint);
    return () => {
      window.removeEventListener('afterprint', afterPrint);
    };
  }, [selectedSale, onGenerateInvoiceNumber, onClose]);

  if (!isOpen || !selectedSale) return null;

  const handlePrint = () => {
    window.print();
  };

  // Display invoice number (will be generated by parent component with global counter)
  const getInvoiceNumber = () => {
    if (selectedSale.invoiceNumber) {
      return selectedSale.invoiceNumber;
    }
    // Placeholder - actual number will be generated on print
    return 'INV-XXX-XXX';
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl w-full max-w-4xl shadow-2xl max-h-[90vh] overflow-hidden flex flex-col">
        <div className="p-6 border-b border-slate-200 flex items-center justify-between bg-gradient-to-r from-blue-600 to-indigo-700">
          <div className="flex items-center gap-3">
            <Printer className="w-6 h-6 text-white" />
            <h3 className="text-white text-xl">Invoice Direct Sales</h3>
          </div>
          <button onClick={onClose} className="text-white hover:bg-white/20 rounded-lg p-2 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-auto p-8 bg-slate-100">
          <div className="bg-white max-w-3xl mx-auto border-2 border-slate-800 rounded-lg p-8 shadow-lg" id="print-invoice-content">
            {/* Header */}
            <div className="border-b-2 border-slate-800 pb-4 mb-6">
              <div className="text-center mb-4">
                <h1 className="text-slate-900 text-3xl mb-2">KWITANSI / INVOICE</h1>
                <p className="text-slate-600">Workshop Management System</p>
                <p className="text-slate-600">Cabang {selectedSale.branch}</p>
              </div>
              <div className="flex justify-between items-center text-sm">
                <div>
                  <p className="text-slate-600">No. Invoice:</p>
                  <p className="text-slate-900 font-mono font-semibold text-lg">
                    {getInvoiceNumber()}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-slate-600">Tanggal:</p>
                  <p className="text-slate-900 font-semibold">{selectedSale.paymentDate || selectedSale.date}</p>
                </div>
              </div>
            </div>

            {/* Telah Terima Dari */}
            <div className="mb-6">
              <div className="flex gap-2 mb-2">
                <p className="text-slate-700">Telah terima dari:</p>
                <p className="text-slate-900 font-semibold border-b border-slate-400 flex-1">{selectedSale.customerName}</p>
              </div>
              {selectedSale.customerAddress && (
                <div className="flex gap-2">
                  <p className="text-slate-700">Alamat:</p>
                  <p className="text-slate-900 border-b border-slate-400 flex-1">{selectedSale.customerAddress}</p>
                </div>
              )}
            </div>

            {/* Uang Terbilang */}
            <div className="mb-6">
              <div className="flex gap-2">
                <p className="text-slate-700">Uang Terbilang:</p>
                <p className="text-slate-900 font-semibold border-b border-slate-400 flex-1 italic capitalize">
                  {numberToWords(Math.round(selectedSale.grandTotal))} rupiah
                </p>
              </div>
            </div>

            {/* Uang Berjumlah */}
            <div className="mb-6">
              <div className="flex gap-2">
                <p className="text-slate-700">Uang Berjumlah:</p>
                <p className="text-slate-900 font-bold text-xl border-b border-slate-400 flex-1">
                  {formatCurrency(selectedSale.grandTotal)}
                </p>
              </div>
            </div>

            {/* Untuk Pembayaran */}
            <div className="mb-6 border border-slate-300 rounded-lg p-6 bg-slate-50">
              <h3 className="text-slate-800 font-semibold mb-4 text-lg">Untuk Pembayaran</h3>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <p className="text-slate-600 text-sm mb-1">No. Faktur:</p>
                  <p className="text-slate-900 font-mono font-semibold text-lg">
                    {selectedSale.notaFakturNumber || `${selectedSale.branch.substring(0, 3).toUpperCase()}-NF-${selectedSale.salesNumber.split('_')[1]}`}
                  </p>
                </div>
                <div>
                  <p className="text-slate-600 text-sm mb-1">No. Sales:</p>
                  <p className="text-slate-900 font-mono font-semibold text-lg">{selectedSale.salesNumber}</p>
                </div>
                <div>
                  <p className="text-slate-600 text-sm mb-1">No. Telepon:</p>
                  <p className="text-slate-900 font-mono font-semibold text-lg">
                    {selectedSale.customerPhone}
                  </p>
                </div>
              </div>
            </div>

            {/* Total Jumlah Uang */}
            <div className="mb-8 border-2 border-slate-800 rounded-lg p-4 bg-slate-100">
              <div className="flex justify-between items-center">
                <span className="text-slate-800 text-lg">TOTAL JUMLAH UANG:</span>
                <span className="text-slate-900 font-bold text-2xl">
                  {formatCurrency(selectedSale.grandTotal)}
                </span>
              </div>
            </div>

            {/* TTD Kasir */}
            <div className="flex justify-end">
              <div className="text-center w-64">
                <p className="text-slate-700 mb-20">Kasir</p>
                <p className="text-slate-700">_________________________</p>
              </div>
            </div>

            {/* Footer Note */}
            <div className="mt-6 pt-4 border-t border-slate-300 text-center">
              <p className="text-slate-500 text-xs italic">* Kwitansi ini sah sebagai bukti pembayaran</p>
            </div>

            {/* Print Count Badge - Only show if this is a reprint (count >= 1) */}
            {selectedSale.invoicePrintCount && selectedSale.invoicePrintCount >= 1 && (
              <div className="mt-6 flex justify-end">
                <div className="print-count-badge inline-flex items-center gap-2 text-slate-600 text-xs">
                  <Printer className="w-3 h-3" />
                  <span>Cetakan ke-{selectedSale.invoicePrintCount + 1}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="border-t border-slate-200 p-6 bg-slate-50 flex gap-3 justify-end">
          <Button variant="outline" onClick={onClose} className="px-6">
            <X className="w-4 h-4 mr-2" />
            Tutup
          </Button>
          <Button 
            onClick={handlePrint}
            className="bg-gradient-to-r from-blue-600 to-indigo-700 px-6"
          >
            <Printer className="w-4 h-4 mr-2" />
            Cetak Invoice
          </Button>
        </div>
      </div>
    </div>
  );
}